apiVersion: v1
kind: Service
metadata:
  labels:
    app: trn
  name: trn
spec:
  ports:
  - protocol: TCP
    name: "82"
    port: 82
    targetPort: 82
  selector:
    app: trn
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trn
  name: trn
spec:
  selector:
    matchLabels:
      app: trn
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trn
    spec:
      #nodeName: devciwknd002
      containers:
      - name: trn
        image: hub.docker.local:5000/bank/trn
        imagePullPolicy: "Always"
        ports:
        - containerPort: 82
        resources:
          limits:
            cpu: "1"
            memory: "1073741824"
          requests:
            cpu: 250m
            memory: "536870912"
      restartPolicy: Always
status: {}
